// <auto-generated />
namespace FabulousDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Pay70 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Pay70));
        
        string IMigrationMetadata.Id
        {
            get { return "201911181023428_Pay70"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
