namespace FabulousDB.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class _13022020 : DbMigration
    {
        public override void Up()
        {
            
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.Inv_transfer_items", "To_store_id", "dbo.Inv_store");
            DropForeignKey("dbo.Inv_transfer_items", "Store_Id", "dbo.Inv_store");
            DropForeignKey("dbo.Inv_transfer_items", "Lot_id", "dbo.Inv_items_serial");
            DropForeignKey("dbo.Inv_transfer_items", "item_id", "dbo.Inv_item");
            DropForeignKey("dbo.Inv_transfer_items", "From_store_id", "dbo.Inv_store");
            DropForeignKey("dbo.Inv_sales_invoice", "Store_id", "dbo.Inv_store");
            DropForeignKey("dbo.Inv_sales_invoice", "Site_id", "dbo.Inv_store_site");
            DropForeignKey("dbo.Inv_sales_invoice", "Currency_id", "dbo.CurrenciesDefinition_Table");
            DropForeignKey("dbo.Inv_sales", "Item_id", "dbo.Inv_item");
            DropForeignKey("dbo.Inv_receive_po_items", "Vat_id", "dbo.C_TaxSetting_table");
            DropForeignKey("dbo.Inv_receive_po_items", "UOM_id", "dbo.Unit_of_measure");
            DropForeignKey("dbo.Inv_receive_po_items", "Table_vat_id", "dbo.C_TaxSetting_table");
            DropForeignKey("dbo.Inv_receive_po_items", "Receive_po_id", "dbo.Inv_receive_po");
            DropForeignKey("dbo.Inv_receive_po_items", "Item_id", "dbo.Inv_item");
            DropForeignKey("dbo.Inv_receive_po_items", "Deduct_id", "dbo.C_TaxSetting_table");
            DropForeignKey("dbo.Inv_receive_po", "Vendore_id", "dbo.Payable_creditor_setting");
            DropForeignKey("dbo.Inv_receive_po", "Store_id", "dbo.Inv_store");
            DropForeignKey("dbo.Inv_receive_po", "Site_id", "dbo.Inv_store_site");
            DropForeignKey("dbo.Inv_store_site", "Store_id", "dbo.Inv_store");
            DropForeignKey("dbo.Inv_receive_po", "PO_id", "dbo.Inv_po");
            DropForeignKey("dbo.Inv_receive_po", "Inv_receive_po_Id", "dbo.Inv_receive_po");
            DropForeignKey("dbo.Inv_receive_po", "Currency_id", "dbo.CurrenciesDefinition_Table");
            DropForeignKey("dbo.Inv_quotation_receiving", "Vendore_Id", "dbo.Payable_creditor_setting");
            DropForeignKey("dbo.Inv_quotation_receiving", "Qutation_num_id", "dbo.Inv_quotation_request");
            DropForeignKey("dbo.Inv_quotation_request", "Vendore_id", "dbo.Payable_creditor_setting");
            DropForeignKey("dbo.Inv_quotation_request", "Pr_no_id", "dbo.Inv_purchase_request");
            DropForeignKey("dbo.Inv_quotation_request", "Item_id", "dbo.Inv_item");
            DropForeignKey("dbo.Inv_quotation_receiving", "Pr_no_id", "dbo.Inv_purchase_request");
            DropForeignKey("dbo.Inv_quotation_receiving", "Currency_id", "dbo.CurrenciesDefinition_Table");
            DropForeignKey("dbo.Inv_purchase", "Item_id", "dbo.Inv_item");
            DropForeignKey("dbo.Inv_pricelist", "Unit_of_measure_id", "dbo.Unit_of_measure");
            DropForeignKey("dbo.Inv_pricelist", "Item_id", "dbo.Inv_item");
            DropForeignKey("dbo.Inv_pricelist", "Currency_id", "dbo.CurrenciesDefinition_Table");
            DropForeignKey("dbo.Inv_po", "Vendore_id", "dbo.Payable_creditor_setting");
            DropForeignKey("dbo.Inv_po", "Pr_no_id", "dbo.Inv_purchase_request");
            DropForeignKey("dbo.Inv_purchase_request", "item_id", "dbo.Inv_item");
            DropForeignKey("dbo.Inv_po_items", "Vat_id", "dbo.C_TaxSetting_table");
            DropForeignKey("dbo.Inv_po_items", "UOM_id", "dbo.Unit_of_measure");
            DropForeignKey("dbo.Inv_po_items", "Table_vat_id", "dbo.C_TaxSetting_table");
            DropForeignKey("dbo.Inv_po_items", "Item_id", "dbo.Inv_item");
            DropForeignKey("dbo.Inv_po_items", "Po_id", "dbo.Inv_po");
            DropForeignKey("dbo.Inv_po_items", "Deduct_id", "dbo.C_TaxSetting_table");
            DropForeignKey("dbo.Inv_po", "Currency_id", "dbo.CurrenciesDefinition_Table");
            DropForeignKey("dbo.Inv_item_gl_accounts", "Variancies_id", "dbo.C_CreateAccount_Table");
            DropForeignKey("dbo.Inv_item_gl_accounts", "Sales_return_id", "dbo.C_CreateAccount_Table");
            DropForeignKey("dbo.Inv_item_gl_accounts", "Sales_id", "dbo.C_CreateAccount_Table");
            DropForeignKey("dbo.Inv_item_gl_accounts", "Returne_id", "dbo.C_CreateAccount_Table");
            DropForeignKey("dbo.Inv_item_gl_accounts", "Purchase_variance_id", "dbo.C_CreateAccount_Table");
            DropForeignKey("dbo.Inv_item_gl_accounts", "Item_group_id", "dbo.Inv_item");
            DropForeignKey("dbo.Inv_item_gl_accounts", "Inventory_id", "dbo.C_CreateAccount_Table");
            DropForeignKey("dbo.Inv_item_gl_accounts", "Damage_id", "dbo.C_CreateAccount_Table");
            DropForeignKey("dbo.Inv_item_gl_accounts", "Cost_of_GS_id", "dbo.C_CreateAccount_Table");
            DropForeignKey("dbo.Inv_gorup_gl_accounts", "Variancies_id", "dbo.C_CreateAccount_Table");
            DropForeignKey("dbo.Inv_gorup_gl_accounts", "Sales_return_id", "dbo.C_CreateAccount_Table");
            DropForeignKey("dbo.Inv_gorup_gl_accounts", "Sales_id", "dbo.C_CreateAccount_Table");
            DropForeignKey("dbo.Inv_gorup_gl_accounts", "Returne_id", "dbo.C_CreateAccount_Table");
            DropForeignKey("dbo.Inv_gorup_gl_accounts", "Purchase_variance_id", "dbo.C_CreateAccount_Table");
            DropForeignKey("dbo.Inv_gorup_gl_accounts", "Item_group_id", "dbo.Inv_item_group");
            DropForeignKey("dbo.Inv_gorup_gl_accounts", "Inventory_id", "dbo.C_CreateAccount_Table");
            DropForeignKey("dbo.Inv_gorup_gl_accounts", "Damage_id", "dbo.C_CreateAccount_Table");
            DropForeignKey("dbo.Inv_gorup_gl_accounts", "Cost_of_GS_id", "dbo.C_CreateAccount_Table");
            DropForeignKey("dbo.Inv_goods_reciept", "Store_id", "dbo.Inv_store");
            DropForeignKey("dbo.Inv_goods_reciept", "Site_id", "dbo.Inv_store");
            DropForeignKey("dbo.Inv_goods_out", "Store_id", "dbo.Inv_store");
            DropForeignKey("dbo.Inv_goods_out", "Site_id", "dbo.Inv_store");
            DropForeignKey("dbo.Inv_adjustment_items", "To_store_id", "dbo.Inv_store");
            DropForeignKey("dbo.Inv_adjustment_items", "Store_Id", "dbo.Inv_store");
            DropForeignKey("dbo.Inv_adjustment_items", "Lot_id", "dbo.Inv_items_serial");
            DropForeignKey("dbo.Inv_items_serial", "Item_id", "dbo.Inv_item");
            DropForeignKey("dbo.Inv_adjustment_items", "item_id", "dbo.Inv_item");
            DropForeignKey("dbo.Inv_item", "Unit_of_measure_id", "dbo.Unit_of_measure");
            DropForeignKey("dbo.Inv_item", "Sales_tax_group_id", "dbo.TaxGroup_table");
            DropForeignKey("dbo.Inv_item", "Purchase_tax_group_id", "dbo.TaxGroup_table");
            DropForeignKey("dbo.Inv_item", "Item_group_id", "dbo.Inv_item_group");
            DropForeignKey("dbo.Inv_item_group", "Unit_of_measure_id", "dbo.Unit_of_measure");
            DropForeignKey("dbo.Inv_item_group", "Sales_tax_group_id", "dbo.TaxGroup_table");
            DropForeignKey("dbo.Inv_item_group", "Purchase_tax_group_id", "dbo.TaxGroup_table");
            DropForeignKey("dbo.Inv_adjustment_items", "From_store_id", "dbo.Inv_store");
            DropIndex("dbo.Inv_transfer_items", new[] { "Store_Id" });
            DropIndex("dbo.Inv_transfer_items", new[] { "Lot_id" });
            DropIndex("dbo.Inv_transfer_items", new[] { "item_id" });
            DropIndex("dbo.Inv_transfer_items", new[] { "To_store_id" });
            DropIndex("dbo.Inv_transfer_items", new[] { "From_store_id" });
            DropIndex("dbo.Inv_sales_invoice", new[] { "Site_id" });
            DropIndex("dbo.Inv_sales_invoice", new[] { "Store_id" });
            DropIndex("dbo.Inv_sales_invoice", new[] { "Currency_id" });
            DropIndex("dbo.Inv_sales", new[] { "Item_id" });
            DropIndex("dbo.Inv_receive_po_items", new[] { "Receive_po_id" });
            DropIndex("dbo.Inv_receive_po_items", new[] { "Deduct_id" });
            DropIndex("dbo.Inv_receive_po_items", new[] { "Vat_id" });
            DropIndex("dbo.Inv_receive_po_items", new[] { "Table_vat_id" });
            DropIndex("dbo.Inv_receive_po_items", new[] { "UOM_id" });
            DropIndex("dbo.Inv_receive_po_items", new[] { "Item_id" });
            DropIndex("dbo.Inv_store_site", new[] { "Store_id" });
            DropIndex("dbo.Inv_receive_po", new[] { "Inv_receive_po_Id" });
            DropIndex("dbo.Inv_receive_po", new[] { "Currency_id" });
            DropIndex("dbo.Inv_receive_po", new[] { "Vendore_id" });
            DropIndex("dbo.Inv_receive_po", new[] { "Site_id" });
            DropIndex("dbo.Inv_receive_po", new[] { "Store_id" });
            DropIndex("dbo.Inv_receive_po", new[] { "PO_id" });
            DropIndex("dbo.Inv_quotation_request", new[] { "Vendore_id" });
            DropIndex("dbo.Inv_quotation_request", new[] { "Item_id" });
            DropIndex("dbo.Inv_quotation_request", new[] { "Pr_no_id" });
            DropIndex("dbo.Inv_quotation_receiving", new[] { "Vendore_Id" });
            DropIndex("dbo.Inv_quotation_receiving", new[] { "Qutation_num_id" });
            DropIndex("dbo.Inv_quotation_receiving", new[] { "Currency_id" });
            DropIndex("dbo.Inv_quotation_receiving", new[] { "Pr_no_id" });
            DropIndex("dbo.Inv_purchase", new[] { "Item_id" });
            DropIndex("dbo.Inv_pricelist", new[] { "Unit_of_measure_id" });
            DropIndex("dbo.Inv_pricelist", new[] { "Currency_id" });
            DropIndex("dbo.Inv_pricelist", new[] { "Item_id" });
            DropIndex("dbo.Inv_purchase_request", new[] { "item_id" });
            DropIndex("dbo.Inv_po_items", new[] { "Po_id" });
            DropIndex("dbo.Inv_po_items", new[] { "Deduct_id" });
            DropIndex("dbo.Inv_po_items", new[] { "Vat_id" });
            DropIndex("dbo.Inv_po_items", new[] { "Table_vat_id" });
            DropIndex("dbo.Inv_po_items", new[] { "UOM_id" });
            DropIndex("dbo.Inv_po_items", new[] { "Item_id" });
            DropIndex("dbo.Inv_po", new[] { "Currency_id" });
            DropIndex("dbo.Inv_po", new[] { "Vendore_id" });
            DropIndex("dbo.Inv_po", new[] { "Pr_no_id" });
            DropIndex("dbo.Inv_item_gl_accounts", new[] { "Purchase_variance_id" });
            DropIndex("dbo.Inv_item_gl_accounts", new[] { "Cost_of_GS_id" });
            DropIndex("dbo.Inv_item_gl_accounts", new[] { "Sales_return_id" });
            DropIndex("dbo.Inv_item_gl_accounts", new[] { "Sales_id" });
            DropIndex("dbo.Inv_item_gl_accounts", new[] { "Variancies_id" });
            DropIndex("dbo.Inv_item_gl_accounts", new[] { "Damage_id" });
            DropIndex("dbo.Inv_item_gl_accounts", new[] { "Returne_id" });
            DropIndex("dbo.Inv_item_gl_accounts", new[] { "Inventory_id" });
            DropIndex("dbo.Inv_item_gl_accounts", new[] { "Item_group_id" });
            DropIndex("dbo.Inv_gorup_gl_accounts", new[] { "Purchase_variance_id" });
            DropIndex("dbo.Inv_gorup_gl_accounts", new[] { "Cost_of_GS_id" });
            DropIndex("dbo.Inv_gorup_gl_accounts", new[] { "Sales_return_id" });
            DropIndex("dbo.Inv_gorup_gl_accounts", new[] { "Sales_id" });
            DropIndex("dbo.Inv_gorup_gl_accounts", new[] { "Variancies_id" });
            DropIndex("dbo.Inv_gorup_gl_accounts", new[] { "Damage_id" });
            DropIndex("dbo.Inv_gorup_gl_accounts", new[] { "Returne_id" });
            DropIndex("dbo.Inv_gorup_gl_accounts", new[] { "Inventory_id" });
            DropIndex("dbo.Inv_gorup_gl_accounts", new[] { "Item_group_id" });
            DropIndex("dbo.Inv_goods_reciept", new[] { "Site_id" });
            DropIndex("dbo.Inv_goods_reciept", new[] { "Store_id" });
            DropIndex("dbo.Inv_goods_out", new[] { "Site_id" });
            DropIndex("dbo.Inv_goods_out", new[] { "Store_id" });
            DropIndex("dbo.Inv_items_serial", new[] { "Item_id" });
            DropIndex("dbo.Inv_item_group", new[] { "Purchase_tax_group_id" });
            DropIndex("dbo.Inv_item_group", new[] { "Sales_tax_group_id" });
            DropIndex("dbo.Inv_item_group", new[] { "Unit_of_measure_id" });
            DropIndex("dbo.Inv_item", new[] { "Purchase_tax_group_id" });
            DropIndex("dbo.Inv_item", new[] { "Sales_tax_group_id" });
            DropIndex("dbo.Inv_item", new[] { "Unit_of_measure_id" });
            DropIndex("dbo.Inv_item", new[] { "Item_group_id" });
            DropIndex("dbo.Inv_adjustment_items", new[] { "Store_Id" });
            DropIndex("dbo.Inv_adjustment_items", new[] { "Lot_id" });
            DropIndex("dbo.Inv_adjustment_items", new[] { "item_id" });
            DropIndex("dbo.Inv_adjustment_items", new[] { "To_store_id" });
            DropIndex("dbo.Inv_adjustment_items", new[] { "From_store_id" });
            DropTable("dbo.Inv_transfer_items");
            DropTable("dbo.Inv_sales_invoice");
            DropTable("dbo.Inv_sales_GS");
            DropTable("dbo.Inv_sales");
            DropTable("dbo.Inv_receive_po_items");
            DropTable("dbo.Inv_store_site");
            DropTable("dbo.Inv_receive_po");
            DropTable("dbo.Inv_quotation_request");
            DropTable("dbo.Inv_quotation_receiving");
            DropTable("dbo.Inv_purchase");
            DropTable("dbo.Inv_pricelist");
            DropTable("dbo.Inv_po_GS");
            DropTable("dbo.Inv_purchase_request");
            DropTable("dbo.Inv_po_items");
            DropTable("dbo.Inv_po");
            DropTable("dbo.Inv_movment_GS");
            DropTable("dbo.Inv_item_gl_accounts");
            DropTable("dbo.Inv_gorup_gl_accounts");
            DropTable("dbo.Inv_goods_reciept");
            DropTable("dbo.Inv_goods_out");
            DropTable("dbo.Inv_items_serial");
            DropTable("dbo.Inv_item_group");
            DropTable("dbo.Inv_item");
            DropTable("dbo.Inv_store");
            DropTable("dbo.Inv_adjustment_items");
        }
    }
}
