// <auto-generated />
namespace FabulousDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class InvGroupNulla : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InvGroupNulla));
        
        string IMigrationMetadata.Id
        {
            get { return "202002191500040_InvGroupNulla"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
