// <auto-generated />
namespace FabulousDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AddInvCutomName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddInvCutomName));
        
        string IMigrationMetadata.Id
        {
            get { return "202004151052008_AddInvCutomName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
