namespace FabulousDB.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class RmoveRequirFromInvGl : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Inv_gorup_gl_accounts", "Cost_of_GS_id", "dbo.C_CreateAccount_Table");
            DropForeignKey("dbo.Inv_gorup_gl_accounts", "Damage_id", "dbo.C_CreateAccount_Table");
            DropForeignKey("dbo.Inv_gorup_gl_accounts", "Purchase_variance_id", "dbo.C_CreateAccount_Table");
            DropForeignKey("dbo.Inv_gorup_gl_accounts", "Returne_id", "dbo.C_CreateAccount_Table");
            DropForeignKey("dbo.Inv_gorup_gl_accounts", "Sales_id", "dbo.C_CreateAccount_Table");
            DropForeignKey("dbo.Inv_gorup_gl_accounts", "Sales_return_id", "dbo.C_CreateAccount_Table");
            DropForeignKey("dbo.Inv_gorup_gl_accounts", "Variancies_id", "dbo.C_CreateAccount_Table");
            DropForeignKey("dbo.Inv_item_gl_accounts", "Cost_of_GS_id", "dbo.C_CreateAccount_Table");
            DropForeignKey("dbo.Inv_item_gl_accounts", "Damage_id", "dbo.C_CreateAccount_Table");
            DropForeignKey("dbo.Inv_item_gl_accounts", "Purchase_variance_id", "dbo.C_CreateAccount_Table");
            DropForeignKey("dbo.Inv_item_gl_accounts", "Returne_id", "dbo.C_CreateAccount_Table");
            DropForeignKey("dbo.Inv_item_gl_accounts", "Sales_id", "dbo.C_CreateAccount_Table");
            DropForeignKey("dbo.Inv_item_gl_accounts", "Sales_return_id", "dbo.C_CreateAccount_Table");
            DropForeignKey("dbo.Inv_item_gl_accounts", "Variancies_id", "dbo.C_CreateAccount_Table");
            DropIndex("dbo.Inv_gorup_gl_accounts", new[] { "Returne_id" });
            DropIndex("dbo.Inv_gorup_gl_accounts", new[] { "Damage_id" });
            DropIndex("dbo.Inv_gorup_gl_accounts", new[] { "Variancies_id" });
            DropIndex("dbo.Inv_gorup_gl_accounts", new[] { "Sales_id" });
            DropIndex("dbo.Inv_gorup_gl_accounts", new[] { "Sales_return_id" });
            DropIndex("dbo.Inv_gorup_gl_accounts", new[] { "Cost_of_GS_id" });
            DropIndex("dbo.Inv_gorup_gl_accounts", new[] { "Purchase_variance_id" });
            DropIndex("dbo.Inv_item_gl_accounts", new[] { "Returne_id" });
            DropIndex("dbo.Inv_item_gl_accounts", new[] { "Damage_id" });
            DropIndex("dbo.Inv_item_gl_accounts", new[] { "Variancies_id" });
            DropIndex("dbo.Inv_item_gl_accounts", new[] { "Sales_id" });
            DropIndex("dbo.Inv_item_gl_accounts", new[] { "Sales_return_id" });
            DropIndex("dbo.Inv_item_gl_accounts", new[] { "Cost_of_GS_id" });
            DropIndex("dbo.Inv_item_gl_accounts", new[] { "Purchase_variance_id" });
            DropIndex("dbo.Inv_quotation_receiving", new[] { "Vendore_Id" });
            AlterColumn("dbo.Inv_gorup_gl_accounts", "Returne_id", c => c.Int());
            AlterColumn("dbo.Inv_gorup_gl_accounts", "Damage_id", c => c.Int());
            AlterColumn("dbo.Inv_gorup_gl_accounts", "Variancies_id", c => c.Int());
            AlterColumn("dbo.Inv_gorup_gl_accounts", "Sales_id", c => c.Int());
            AlterColumn("dbo.Inv_gorup_gl_accounts", "Sales_return_id", c => c.Int());
            AlterColumn("dbo.Inv_gorup_gl_accounts", "Cost_of_GS_id", c => c.Int());
            AlterColumn("dbo.Inv_gorup_gl_accounts", "Purchase_variance_id", c => c.Int());
            AlterColumn("dbo.Inv_item_gl_accounts", "Returne_id", c => c.Int());
            AlterColumn("dbo.Inv_item_gl_accounts", "Damage_id", c => c.Int());
            AlterColumn("dbo.Inv_item_gl_accounts", "Variancies_id", c => c.Int());
            AlterColumn("dbo.Inv_item_gl_accounts", "Sales_id", c => c.Int());
            AlterColumn("dbo.Inv_item_gl_accounts", "Sales_return_id", c => c.Int());
            AlterColumn("dbo.Inv_item_gl_accounts", "Cost_of_GS_id", c => c.Int());
            AlterColumn("dbo.Inv_item_gl_accounts", "Purchase_variance_id", c => c.Int());
            AlterColumn("dbo.Inv_quotation_receiving", "Vendore_Id", c => c.Int());
            AlterColumn("dbo.Inv_quotation_receiving", "Vendore_id", c => c.Int(nullable: false));
            CreateIndex("dbo.Inv_gorup_gl_accounts", "Returne_id");
            CreateIndex("dbo.Inv_gorup_gl_accounts", "Damage_id");
            CreateIndex("dbo.Inv_gorup_gl_accounts", "Variancies_id");
            CreateIndex("dbo.Inv_gorup_gl_accounts", "Sales_id");
            CreateIndex("dbo.Inv_gorup_gl_accounts", "Sales_return_id");
            CreateIndex("dbo.Inv_gorup_gl_accounts", "Cost_of_GS_id");
            CreateIndex("dbo.Inv_gorup_gl_accounts", "Purchase_variance_id");
            CreateIndex("dbo.Inv_item_gl_accounts", "Returne_id");
            CreateIndex("dbo.Inv_item_gl_accounts", "Damage_id");
            CreateIndex("dbo.Inv_item_gl_accounts", "Variancies_id");
            CreateIndex("dbo.Inv_item_gl_accounts", "Sales_id");
            CreateIndex("dbo.Inv_item_gl_accounts", "Sales_return_id");
            CreateIndex("dbo.Inv_item_gl_accounts", "Cost_of_GS_id");
            CreateIndex("dbo.Inv_item_gl_accounts", "Purchase_variance_id");
            CreateIndex("dbo.Inv_quotation_receiving", "Vendore_Id");
            AddForeignKey("dbo.Inv_gorup_gl_accounts", "Cost_of_GS_id", "dbo.C_CreateAccount_Table", "C_AID");
            AddForeignKey("dbo.Inv_gorup_gl_accounts", "Damage_id", "dbo.C_CreateAccount_Table", "C_AID");
            AddForeignKey("dbo.Inv_gorup_gl_accounts", "Purchase_variance_id", "dbo.C_CreateAccount_Table", "C_AID");
            AddForeignKey("dbo.Inv_gorup_gl_accounts", "Returne_id", "dbo.C_CreateAccount_Table", "C_AID");
            AddForeignKey("dbo.Inv_gorup_gl_accounts", "Sales_id", "dbo.C_CreateAccount_Table", "C_AID");
            AddForeignKey("dbo.Inv_gorup_gl_accounts", "Sales_return_id", "dbo.C_CreateAccount_Table", "C_AID");
            AddForeignKey("dbo.Inv_gorup_gl_accounts", "Variancies_id", "dbo.C_CreateAccount_Table", "C_AID");
            AddForeignKey("dbo.Inv_item_gl_accounts", "Cost_of_GS_id", "dbo.C_CreateAccount_Table", "C_AID");
            AddForeignKey("dbo.Inv_item_gl_accounts", "Damage_id", "dbo.C_CreateAccount_Table", "C_AID");
            AddForeignKey("dbo.Inv_item_gl_accounts", "Purchase_variance_id", "dbo.C_CreateAccount_Table", "C_AID");
            AddForeignKey("dbo.Inv_item_gl_accounts", "Returne_id", "dbo.C_CreateAccount_Table", "C_AID");
            AddForeignKey("dbo.Inv_item_gl_accounts", "Sales_id", "dbo.C_CreateAccount_Table", "C_AID");
            AddForeignKey("dbo.Inv_item_gl_accounts", "Sales_return_id", "dbo.C_CreateAccount_Table", "C_AID");
            AddForeignKey("dbo.Inv_item_gl_accounts", "Variancies_id", "dbo.C_CreateAccount_Table", "C_AID");
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.Inv_item_gl_accounts", "Variancies_id", "dbo.C_CreateAccount_Table");
            DropForeignKey("dbo.Inv_item_gl_accounts", "Sales_return_id", "dbo.C_CreateAccount_Table");
            DropForeignKey("dbo.Inv_item_gl_accounts", "Sales_id", "dbo.C_CreateAccount_Table");
            DropForeignKey("dbo.Inv_item_gl_accounts", "Returne_id", "dbo.C_CreateAccount_Table");
            DropForeignKey("dbo.Inv_item_gl_accounts", "Purchase_variance_id", "dbo.C_CreateAccount_Table");
            DropForeignKey("dbo.Inv_item_gl_accounts", "Damage_id", "dbo.C_CreateAccount_Table");
            DropForeignKey("dbo.Inv_item_gl_accounts", "Cost_of_GS_id", "dbo.C_CreateAccount_Table");
            DropForeignKey("dbo.Inv_gorup_gl_accounts", "Variancies_id", "dbo.C_CreateAccount_Table");
            DropForeignKey("dbo.Inv_gorup_gl_accounts", "Sales_return_id", "dbo.C_CreateAccount_Table");
            DropForeignKey("dbo.Inv_gorup_gl_accounts", "Sales_id", "dbo.C_CreateAccount_Table");
            DropForeignKey("dbo.Inv_gorup_gl_accounts", "Returne_id", "dbo.C_CreateAccount_Table");
            DropForeignKey("dbo.Inv_gorup_gl_accounts", "Purchase_variance_id", "dbo.C_CreateAccount_Table");
            DropForeignKey("dbo.Inv_gorup_gl_accounts", "Damage_id", "dbo.C_CreateAccount_Table");
            DropForeignKey("dbo.Inv_gorup_gl_accounts", "Cost_of_GS_id", "dbo.C_CreateAccount_Table");
            DropIndex("dbo.Inv_quotation_receiving", new[] { "Vendore_Id" });
            DropIndex("dbo.Inv_item_gl_accounts", new[] { "Purchase_variance_id" });
            DropIndex("dbo.Inv_item_gl_accounts", new[] { "Cost_of_GS_id" });
            DropIndex("dbo.Inv_item_gl_accounts", new[] { "Sales_return_id" });
            DropIndex("dbo.Inv_item_gl_accounts", new[] { "Sales_id" });
            DropIndex("dbo.Inv_item_gl_accounts", new[] { "Variancies_id" });
            DropIndex("dbo.Inv_item_gl_accounts", new[] { "Damage_id" });
            DropIndex("dbo.Inv_item_gl_accounts", new[] { "Returne_id" });
            DropIndex("dbo.Inv_gorup_gl_accounts", new[] { "Purchase_variance_id" });
            DropIndex("dbo.Inv_gorup_gl_accounts", new[] { "Cost_of_GS_id" });
            DropIndex("dbo.Inv_gorup_gl_accounts", new[] { "Sales_return_id" });
            DropIndex("dbo.Inv_gorup_gl_accounts", new[] { "Sales_id" });
            DropIndex("dbo.Inv_gorup_gl_accounts", new[] { "Variancies_id" });
            DropIndex("dbo.Inv_gorup_gl_accounts", new[] { "Damage_id" });
            DropIndex("dbo.Inv_gorup_gl_accounts", new[] { "Returne_id" });
            AlterColumn("dbo.Inv_quotation_receiving", "Vendore_id", c => c.Int());
            AlterColumn("dbo.Inv_quotation_receiving", "Vendore_Id", c => c.Int(nullable: false));
            AlterColumn("dbo.Inv_item_gl_accounts", "Purchase_variance_id", c => c.Int(nullable: false));
            AlterColumn("dbo.Inv_item_gl_accounts", "Cost_of_GS_id", c => c.Int(nullable: false));
            AlterColumn("dbo.Inv_item_gl_accounts", "Sales_return_id", c => c.Int(nullable: false));
            AlterColumn("dbo.Inv_item_gl_accounts", "Sales_id", c => c.Int(nullable: false));
            AlterColumn("dbo.Inv_item_gl_accounts", "Variancies_id", c => c.Int(nullable: false));
            AlterColumn("dbo.Inv_item_gl_accounts", "Damage_id", c => c.Int(nullable: false));
            AlterColumn("dbo.Inv_item_gl_accounts", "Returne_id", c => c.Int(nullable: false));
            AlterColumn("dbo.Inv_gorup_gl_accounts", "Purchase_variance_id", c => c.Int(nullable: false));
            AlterColumn("dbo.Inv_gorup_gl_accounts", "Cost_of_GS_id", c => c.Int(nullable: false));
            AlterColumn("dbo.Inv_gorup_gl_accounts", "Sales_return_id", c => c.Int(nullable: false));
            AlterColumn("dbo.Inv_gorup_gl_accounts", "Sales_id", c => c.Int(nullable: false));
            AlterColumn("dbo.Inv_gorup_gl_accounts", "Variancies_id", c => c.Int(nullable: false));
            AlterColumn("dbo.Inv_gorup_gl_accounts", "Damage_id", c => c.Int(nullable: false));
            AlterColumn("dbo.Inv_gorup_gl_accounts", "Returne_id", c => c.Int(nullable: false));
            CreateIndex("dbo.Inv_quotation_receiving", "Vendore_Id");
            CreateIndex("dbo.Inv_item_gl_accounts", "Purchase_variance_id");
            CreateIndex("dbo.Inv_item_gl_accounts", "Cost_of_GS_id");
            CreateIndex("dbo.Inv_item_gl_accounts", "Sales_return_id");
            CreateIndex("dbo.Inv_item_gl_accounts", "Sales_id");
            CreateIndex("dbo.Inv_item_gl_accounts", "Variancies_id");
            CreateIndex("dbo.Inv_item_gl_accounts", "Damage_id");
            CreateIndex("dbo.Inv_item_gl_accounts", "Returne_id");
            CreateIndex("dbo.Inv_gorup_gl_accounts", "Purchase_variance_id");
            CreateIndex("dbo.Inv_gorup_gl_accounts", "Cost_of_GS_id");
            CreateIndex("dbo.Inv_gorup_gl_accounts", "Sales_return_id");
            CreateIndex("dbo.Inv_gorup_gl_accounts", "Sales_id");
            CreateIndex("dbo.Inv_gorup_gl_accounts", "Variancies_id");
            CreateIndex("dbo.Inv_gorup_gl_accounts", "Damage_id");
            CreateIndex("dbo.Inv_gorup_gl_accounts", "Returne_id");
            AddForeignKey("dbo.Inv_item_gl_accounts", "Variancies_id", "dbo.C_CreateAccount_Table", "C_AID", cascadeDelete: true);
            AddForeignKey("dbo.Inv_item_gl_accounts", "Sales_return_id", "dbo.C_CreateAccount_Table", "C_AID", cascadeDelete: true);
            AddForeignKey("dbo.Inv_item_gl_accounts", "Sales_id", "dbo.C_CreateAccount_Table", "C_AID", cascadeDelete: true);
            AddForeignKey("dbo.Inv_item_gl_accounts", "Returne_id", "dbo.C_CreateAccount_Table", "C_AID", cascadeDelete: true);
            AddForeignKey("dbo.Inv_item_gl_accounts", "Purchase_variance_id", "dbo.C_CreateAccount_Table", "C_AID", cascadeDelete: true);
            AddForeignKey("dbo.Inv_item_gl_accounts", "Damage_id", "dbo.C_CreateAccount_Table", "C_AID", cascadeDelete: true);
            AddForeignKey("dbo.Inv_item_gl_accounts", "Cost_of_GS_id", "dbo.C_CreateAccount_Table", "C_AID", cascadeDelete: true);
            AddForeignKey("dbo.Inv_gorup_gl_accounts", "Variancies_id", "dbo.C_CreateAccount_Table", "C_AID", cascadeDelete: true);
            AddForeignKey("dbo.Inv_gorup_gl_accounts", "Sales_return_id", "dbo.C_CreateAccount_Table", "C_AID", cascadeDelete: true);
            AddForeignKey("dbo.Inv_gorup_gl_accounts", "Sales_id", "dbo.C_CreateAccount_Table", "C_AID", cascadeDelete: true);
            AddForeignKey("dbo.Inv_gorup_gl_accounts", "Returne_id", "dbo.C_CreateAccount_Table", "C_AID", cascadeDelete: true);
            AddForeignKey("dbo.Inv_gorup_gl_accounts", "Purchase_variance_id", "dbo.C_CreateAccount_Table", "C_AID", cascadeDelete: true);
            AddForeignKey("dbo.Inv_gorup_gl_accounts", "Damage_id", "dbo.C_CreateAccount_Table", "C_AID", cascadeDelete: true);
            AddForeignKey("dbo.Inv_gorup_gl_accounts", "Cost_of_GS_id", "dbo.C_CreateAccount_Table", "C_AID", cascadeDelete: true);
        }
    }
}
