// <auto-generated />
namespace FabulousDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class InvRec1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InvRec1));
        
        string IMigrationMetadata.Id
        {
            get { return "202004221254192_InvRec1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
