// <auto-generated />
namespace FabulousDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Inv_item_options : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Inv_item_options));
        
        string IMigrationMetadata.Id
        {
            get { return "202005191127261_Inv_item_options"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
